twig:
    # default_path: '%kernel.project_dir%/templates'
    paths:
      '%kernel.project_dir%/src/Presentation/Web/FrontOffice/templates': FrontOffice
      '%kernel.project_dir%/src/Presentation/Web/BackOffice/templates': BackOffice
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
